### ISSUE TITLE
No module named libgen-uploader / <Failure: 'NoneType' object is not subscriptable>

### ISSUE THREAD

**Issue by BrianZbr** [ftruzzi/libgen_uploader#9]
I'm following the readme closely without luck.

When I try to run it as a command, I get `No module named libgen-uploader`. This is the same whether I use a venv or my OS.
 
When I try to use it as a library, it imports fine and I'm able to set up a metadata instance. But when I try to upload with anything like `u.upload_scitech("file-that-exists-working-directory.pdf", metadata = m)`, I get the error `<Failure: 'NoneType' object is not subscriptable>`.

Any advice?

**Comment by ftruzzi** [comment]
Hi,

Apologies for the issue, I haven't used the library for more than a year and I was not aware of it.

It seems to be a problem of dependencies that need to be upgraded + a change of user agent (Libgen could have banned the user agent, but I would be kind of surprised).

Unfortunately, I don't have books that are not on Libgen, so I can't test the full upload flow as I get a "File already existing" error before being able to enter the metadata.

Would you mind trying the version on the `fixes` branch, and letting me know if it fixes it for you? If it does, I'll publish a new version on pypi.

`pip install git+https://github.com/ftruzzi/libgen_uploader.git@fixes`

> When I try to run it as a command, I get No module named libgen-uploader.

You need to write it with an underscore (`libgen_uploader`), it should work from command line as well.

Thanks!

**Comment by BrianZbr** [comment]
Thank you for the fast response! I finally am trying this now but unfortunately I am seeing the same result with this new branch.

**Comment by ftruzzi** [comment]
Hi @BrianZbr,

I had time to find a book and test the new version, and I was able to upload a book with it. I'll try to publish a new version on PyPi soon.

I would suggest that you try on a fresh Python env with the new version and dependencies, and run e.g.:

`python -m libgen_uploader -d --scitech book.epub`

If you need help with getting this to work, I'll be happy to chat or talk with you (you can email me at [myname]@[mysurname].me)
